## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [23]:
arr = np.zeros(10)
print(arr)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Создать вектор размера 10, заполненный единицами

In [24]:
arr = np.ones(10)
print(arr)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


Создать вектор размера 10, заполненный числом 2.5

In [25]:
arr = np.full(10, 2.5)
print(arr)

[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


Развернуть вектор (первый становится последним)

In [26]:
arr = np.arange(10)[::-1]
print(arr)

[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [27]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [31]:
arr = np.nonzero([1,2,0,0,4,0])
print(arr)

(array([0, 1, 4], dtype=int64),)


Создать 3x3 единичную матрицу

In [3]:
arr = np.eye(3)
print(arr)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Создать массив 3x3x3 со случайными значениями

In [5]:
arr = np.random.random((3,3,3))
print(arr)

[[[ 0.83254756  0.32332038  0.85390811]
  [ 0.11129047  0.11377618  0.4632496 ]
  [ 0.59220897  0.24363822  0.6428959 ]]

 [[ 0.71661413  0.93890399  0.8170405 ]
  [ 0.7312601   0.37609973  0.37802771]
  [ 0.67973211  0.29394163  0.49887762]]

 [[ 0.29337541  0.51832514  0.49689198]
  [ 0.95434173  0.28250467  0.02167234]
  [ 0.3193307   0.60007536  0.32413002]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [7]:
arr = np.random.random(30)
mid = arr.mean()
print(arr)
print(mid)

[ 0.32329352  0.48555462  0.10985582  0.43998616  0.28985986  0.67301588
  0.27232252  0.38240626  0.92684801  0.46998549  0.92637734  0.39497444
  0.07025188  0.51210181  0.60817209  0.11549459  0.5189905   0.61186283
  0.17838807  0.3471586   0.03879418  0.14434134  0.37247819  0.87744184
  0.49259443  0.32378014  0.56369734  0.59710565  0.65422139  0.73146445]
0.448427307491


Перемножить матрицы 5x3 и 3x2

In [17]:
arr = np.dot(np.ones((5,3)), np.ones((3,2)))
print(arr)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [28]:
arr = np.linspace(0, 1, 12)[1:-1]
print(arr)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


Заменить максимальный элемент на ноль

In [38]:
arr = np.random.random(10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[ 0.16582632  0.0591039   0.16277841  0.36399119  0.57050679  0.12785576
  0.76274703  0.09266525  0.13556581  0.88085487]
[ 0.16582632  0.0591039   0.16277841  0.36399119  0.57050679  0.12785576
  0.76274703  0.09266525  0.13556581  0.        ]


Преобразовать массив из float в int

In [36]:
arr = np.arange(10, dtype=np.float32)
arr = arr.astype(np.int, copy=False)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [46]:
from scipy import spatial as sp

arr = np.random.random((10,2))
dist = sp.distance.cdist(arr,arr)
print(dist)

[[ 0.          0.20421968  0.49174461  0.06829302  1.12284249  0.52537248
   0.56007432  1.12476646  0.55751434  0.13535716]
 [ 0.20421968  0.          0.45142017  0.2329063   0.91990628  0.32413007
   0.41718421  0.92258391  0.42060873  0.30620695]
 [ 0.49174461  0.45142017  0.          0.44143902  0.98170353  0.6146942
   0.27198069  0.97045978  0.8397025   0.44225201]
 [ 0.06829302  0.2329063   0.44143902  0.          1.13737124  0.55673217
   0.53920103  1.13753317  0.61527963  0.07582389]
 [ 1.12284249  0.91990628  0.98170353  1.13737124  0.          0.62410621
   0.710519    0.02978976  0.83170572  1.19967886]
 [ 0.52537248  0.32413007  0.6146942   0.55673217  0.62410621  0.
   0.41861848  0.63210757  0.29884458  0.62880212]
 [ 0.56007432  0.41718421  0.27198069  0.53920103  0.710519    0.41861848
   0.          0.7001225   0.69642703  0.57630794]
 [ 1.12476646  0.92258391  0.97045978  1.13753317  0.02978976  0.63210757
   0.7001225   0.          0.8476197   1.1987186 ]
 [ 0.5575

Случайно расположить p элементов в 2D массив

In [57]:
n = 10
p = 5
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False), 1)
print(arr)

[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [59]:
arr = np.array([1,2,3,4,5])
zcount = 3
arr1 = np.zeros(len(arr) + (len(arr)-1)*(zcount))
print(arr1)
arr1[::zcount+1] = arr
print(arr1)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

Найти n наибольших значений в массиве

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

Посмотреть первые 5 записей

Сколько наблюдений в наборе данных?


Сколько столбцов в наборе данных?

Напечатайте все названия столбцов

Какое название у 105 столбца?

Какой тип наблюдений в 105 столбце?

Как проиндексирован набор данных?

Каково значение имени продукта в 19-м наблюдении?

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?